services:
  - type: web
    name: plant-medicator-backend
    runtime: python  # ¡Este campo es obligatorio!
    python:
      version: "3.11.8"  # Sintaxis exacta requerida
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python -m uvicorn app.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: SECRET_KEY
        value: GROF*_*09
